/* NP.T — player-facing text lookup with inline English fallback.
 *
 *   NP.T('system.battle.used', '{user} used {move}!', { user: 'Konko', move: 'Pounce' })  -> string
 *   NP.TP('story.lab.intro.1', 'Ah, {player}!\\pThere you are!', vars)                   -> array of page strings
 *
 * If the writing team's NP.text.get(key) returns an array of page strings for `key`, that replaces the fallback.
 * `{var}` placeholders are filled from `vars` first, then {player}/{rival} via NP.fmt. Missing/throwing NP.text is fine.
 * Every key used in the code is listed (with fallback + variables) in docs/engine-text-keys.md (generated by
 * `node tools/gen-text-keys.mjs`, which scans for NP.T / T( / TP( calls with a string-literal key and fallback).
 */
(function (root) {
  'use strict';
  const NP = (root.NP = root.NP || {});

  function pages(key) {
    try {
      const L = NP.text && NP.text.get && NP.text.get(key);
      return L && L.length ? Array.from(L) : null;
    } catch (e) {
      return null;
    }
  }
  function subst(s, vars) {
    s = String(s);
    if (vars) s = s.replace(/\{(\w+)\}/g, (m, k) => (vars[k] !== undefined && vars[k] !== null ? String(vars[k]) : m));
    return NP.fmt ? NP.fmt(s) : s;
  }

  NP.T = function (key, fallback, vars) {
    const L = pages(key);
    return subst(L ? L.join('\\p') : Array.isArray(fallback) ? fallback.join('\\p') : fallback, vars);
  };
  NP.TP = function (key, fallback, vars) {
    const L = pages(key) || (Array.isArray(fallback) ? fallback : [fallback]);
    return L.map((s) => subst(s, vars));
  };
  NP.textOverride = pages;
})(typeof globalThis !== 'undefined' ? globalThis : window);
