/* src/audio/notation.js — NP.audio core: music/SFX text notation parser, compiler (text -> timed events), voice model, validator, DSL helpers.
 * Pure data crunching, no WebAudio here: the same compiled events and the same voice model (`voices`) drive the browser synth (engine.js)
 * and the Node renderer / loudness tools (tools/audio-synth.mjs). Notation reference: docs/audio.md */
(function (root) {
  'use strict';
  const NP = (root.NP = root.NP || {});
  const A = (NP.audio = NP.audio || {});
  NP.data = NP.data || {};
  NP.data.songs = NP.data.songs || {};
  NP.data.sfx = NP.data.sfx || {};
  A.levels = A.levels || { m: {}, s: {}, c: {} }; // measured gains, filled by src/audio/levels.js (generated by tools/audio-tune.mjs)

  const PC = { c: 0, d: 2, e: 4, f: 5, g: 7, a: 9, b: 11 };
  const NAMES = ['c', 'c#', 'd', 'd#', 'e', 'f', 'f#', 'g', 'g#', 'a', 'a#', 'b'];
  const DUTY = [0.125, 0.25, 0.5, 0.75];
  const CHANNELS = ['p1', 'p2', 'tri', 'noi'];
  const DEFAULT_INST = {
    p1: { duty: 2, vol: 11, env: 'hold', gate: 0.9 },
    p2: { duty: 1, vol: 7, env: 'hold', gate: 0.85 },
    tri: { vol: 13, env: 'hold', gate: 0.95 },
    noi: { vol: 9 },
  };
  const CHORDS = { '': [0, 4, 7, 12], m: [0, 3, 7, 12], 7: [0, 4, 7, 10], m7: [0, 3, 7, 10], maj7: [0, 4, 7, 11], sus: [0, 5, 7, 12], dim: [0, 3, 6, 12], add9: [0, 4, 7, 14] };
  // Drum kit, shared by the browser synth and the Node renderer. tone: pitch-dropping sine; noise: filtered noise burst.
  const DRUMS = {
    k: { tone: { f: 160, f2: 42, dur: 0.13, vol: 1 }, noise: { filt: 'lp', fc: 500, dur: 0.02, vol: 0.25 } }, // kick
    s: { tone: { f: 210, f2: 150, dur: 0.06, vol: 0.35 }, noise: { filt: 'bp', fc: 2600, dur: 0.13, vol: 0.85 } }, // snare
    h: { noise: { filt: 'hp', fc: 7500, dur: 0.035, vol: 0.5 } }, // closed hat
    o: { noise: { filt: 'hp', fc: 6500, dur: 0.16, vol: 0.5 } }, // open hat
    x: { noise: { filt: 'hp', fc: 4000, dur: 0.7, vol: 0.6 } }, // crash
    t: { tone: { f: 240, f2: 90, dur: 0.16, vol: 0.8 } }, // tom
    m: { tone: { f: 120, f2: 66, dur: 0.24, vol: 0.95 } }, // low tom / timpani
    w: { tone: { f: 950, f2: 720, dur: 0.05, vol: 0.6 } }, // wood block
    a: { tone: { f: 1850, f2: 1750, dur: 0.16, vol: 0.3 }, noise: { filt: 'bp', fc: 4300, dur: 0.05, vol: 0.4 } }, // anvil / metal clink
    g: { noise: { filt: 'hp', fc: 5200, dur: 0.07, vol: 0.28 } }, // shaker
    c: { noise: { filt: 'bp', fc: 1600, dur: 0.1, vol: 0.85 } }, // clap
  };
  const DRUM_KEYS = Object.keys(DRUMS).join('');
  // Per-voice-type mix constants (amplitude per unit `vol`), calibrated with tools/audio-tune.mjs. Pulse duties are loudness-compensated.
  const MIX = { p1: 0.13, p2: 0.11, tri: 0.2, sin: 0.18, nz: 0.28, dt: 0.2, dn: 0.32 };
  const PULSE_EXP = 0.9;
  const ENV_VERSION = 1;
  const pulseComp = (i) => {
    const d = DUTY[i === undefined ? 2 : i];
    return Math.pow(Math.max(d, 1 - d) / Math.sqrt(d * (1 - d)), PULSE_EXP);
  };
  const ENV_CODES = { h: 'hold', p: 'pluck', d: 'decay', s: 'swell' };

  function midiOf(name) {
    const m = /^([a-g])([#b]?)(-?\d)$/.exec(name);
    if (!m) return NaN;
    return 12 * (+m[3] + 1) + PC[m[1]] + (m[2] === '#' ? 1 : m[2] === 'b' ? -1 : 0);
  }
  const nameOf = (m) => NAMES[((m % 12) + 12) % 12] + (Math.floor(m / 12) - 1);
  const hz = (m) => 440 * Math.pow(2, (m - 69) / 12);

  /** 'Am7' / 'F#3' / 'Bb2' -> { root:midi, tones:[midi x4] }  (octave digit = root octave, default 3) */
  function chord(str) {
    const m = /^([A-G])([#b]?)(maj7|m7|dim|sus|add9|m|7|)(\d)?$/.exec(str);
    if (!m) return null;
    const root = 12 * ((m[4] === undefined ? 3 : +m[4]) + 1) + PC[m[1].toLowerCase()] + (m[2] === '#' ? 1 : m[2] === 'b' ? -1 : 0);
    return { root, tones: CHORDS[m[3]].map((i) => root + i) };
  }

  // ---------- amplitude envelopes / voice model (shared by engine.js and the Node renderer) ----------
  /** Piecewise-linear envelope [[t, v], ...] for a note of `dur` seconds and peak `amp`. */
  function envPoints(env, dur, amp) {
    const z = 0.0001;
    let pts;
    if (env === 'swell') pts = [[0, z], [dur * 0.45, amp], [dur * 0.9, amp], [dur, z]];
    else if (env === 'pluck') pts = [[0, z], [0.004, amp], [Math.max(0.02, dur * 0.85), amp * 0.45], [dur, z]];
    else if (env === 'decay') pts = [[0, z], [0.003, amp], [dur * 0.92, amp * 0.12], [dur, z]];
    else pts = [[0, z], [0.004, amp], [Math.max(0.006, dur - 0.012), amp], [dur, z]];
    let prev = 0;
    for (const p of pts) { p[0] = Math.min(dur, Math.max(prev, p[0])); prev = p[0]; }
    return pts;
  }

  /** Turn one compiled event into primitive voices: {k:'osc',wave,duty,f,f2,vib,dur,amp,env} / {k:'noise',filt,fc,fc2,q,dur,amp,env}. */
  function voices(e) {
    const g = e.g === undefined ? 1 : e.g;
    const vol = e.vol * g;
    const out = [];
    if (e.ch === 'p1' || e.ch === 'p2') {
      out.push({ k: 'osc', wave: 'pulse', duty: e.duty === undefined ? 2 : e.duty, f: e.f, f2: e.f2 || e.f, vib: e.vib, dur: e.dur, amp: vol * MIX[e.ch] * pulseComp(e.duty), env: e.env || 'hold' });
    } else if (e.ch === 'tri') {
      out.push({ k: 'osc', wave: 'triangle', f: e.f, f2: e.f2 || e.f, vib: e.vib, dur: e.dur, amp: vol * MIX.tri, env: e.env || 'hold' });
    } else if (e.ch === 'sin') {
      out.push({ k: 'osc', wave: 'sine', f: e.f, f2: e.f2 || e.f, vib: e.vib, dur: e.dur, amp: vol * MIX.sin, env: e.env || 'hold' });
    } else if (e.ch === 'noi') {
      if (e.d === 'n') {
        out.push({ k: 'noise', filt: 'bp', fc: e.f, fc2: e.f2 || e.f, q: 1.2, dur: e.dur, amp: vol * MIX.nz, env: e.env || 'decay' });
      } else {
        const k = DRUMS[e.d];
        if (k && k.tone) out.push({ k: 'osc', wave: 'sine', f: k.tone.f, f2: k.tone.f2, dur: k.tone.dur, amp: vol * k.tone.vol * MIX.dt, env: 'decay' });
        if (k && k.noise) out.push({ k: 'noise', filt: k.noise.filt, fc: k.noise.fc, fc2: k.noise.fc, q: k.noise.filt === 'bp' ? 1.2 : 1, dur: k.noise.dur, amp: vol * k.noise.vol * MIX.dn, env: 'decay' });
      }
    }
    return out;
  }

  // ---------- track text -> items ----------
  function expand(str) {
    const raw = String(str)
      .replace(/\|/g, ' | ')
      .replace(/\[/g, ' [ ')
      .replace(/\]x(\d+)/g, ' ]x$1 ')
      .trim()
      .split(/\s+/)
      .filter(Boolean);
    const stack = [[]];
    const errs = [];
    for (const t of raw) {
      if (t === '[') stack.push([]);
      else if (t.startsWith(']x')) {
        if (stack.length < 2) { errs.push('unmatched ]'); continue; }
        const body = stack.pop();
        const n = +t.slice(2);
        const top = stack[stack.length - 1];
        for (let i = 0; i < n; i++) for (const b of body) top.push(b);
      } else stack[stack.length - 1].push(t);
    }
    if (stack.length !== 1) errs.push('unmatched [');
    return { tokens: stack[0], errs };
  }

  /** Parse one track. kind: 'p1'|'p2'|'tri'|'noi'. Returns {items, steps, bars, errors}. */
  function parseTrack(str, kind, inst) {
    const { tokens, errs } = expand(str);
    const errors = errs.slice();
    const items = [];
    const bars = [];
    const drumRe = new RegExp('^[' + DRUM_KEYS + ']+$');
    let step = 0, len = 2, vol = inst.vol, duty = inst.duty, env = inst.env;
    for (const tok of tokens) {
      if (tok === '|') { bars.push(step); continue; }
      if (tok[0] === '%') {
        const c = tok[1], v = tok.slice(2);
        if (c === 'd' && /^[0-3]$/.test(v)) duty = +v;
        else if (c === 'v' && /^\d{1,2}$/.test(v) && +v <= 15) vol = +v;
        else if (c === 'e' && /^[hpds]$/.test(v)) env = ENV_CODES[v];
        else errors.push('bad control ' + tok);
        continue;
      }
      const [head, l] = tok.split(':');
      if (l !== undefined) {
        if (!/^\d+$/.test(l) || +l < 1) { errors.push('bad length ' + tok); continue; }
        len = +l;
      }
      if (head === 'r') { step += len; continue; }
      if (kind === 'noi') {
        if (drumRe.test(head)) { for (const d of head) items.push({ s: step, l: len, drum: d, v: vol }); step += len; }
        else errors.push('bad drum ' + tok);
        continue;
      }
      if (head[0] === '^') {
        const ch = chord(head.slice(1));
        if (!ch) { errors.push('bad chord ' + tok); continue; }
        const rate = inst.arp || 1;
        for (let i = 0, k = 0; i < len; i += rate, k++) {
          items.push({ s: step + i, l: Math.min(rate, len - i), midi: ch.tones[k % 4], v: vol, duty, env, arp: true });
        }
        step += len;
        continue;
      }
      const midi = midiOf(head);
      if (isNaN(midi)) { errors.push('bad token ' + tok); continue; }
      items.push({ s: step, l: len, midi, v: vol, duty, env });
      step += len;
    }
    return { items, steps: step, bars, errors };
  }

  function instOf(def, ch) {
    return Object.assign({}, DEFAULT_INST[ch], (def.inst && def.inst[ch]) || {});
  }

  // ---------- fingerprints (levels.js is only valid for the data it was measured on) ----------
  function fnvStr(s, h) {
    h = h === undefined ? 0x811c9dc5 : h;
    for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 0x01000193); }
    return h >>> 0;
  }
  const synthSig = () => JSON.stringify([MIX, DRUMS, PULSE_EXP, ENV_VERSION]);
  function fingerprint(events, extra) {
    let h = fnvStr(synthSig());
    if (extra) h = fnvStr(String(extra), h);
    for (const e of events) {
      h = fnvStr([e.t.toFixed(4), e.ch, e.f ? e.f.toFixed(2) : '', e.f2 ? e.f2.toFixed(2) : '', e.d || '', e.dur.toFixed(4), e.vol.toFixed(3),
        e.duty === undefined ? '' : e.duty, e.env || '', e.vib ? e.vib.rate.toFixed(2) + ',' + e.vib.depth.toFixed(3) + ',' + (e.vib.delay || 0) : ''].join('|') + ';', h);
    }
    return h.toString(16).padStart(8, '0');
  }

  const cache = {};
  /** Compile a song definition into { events, total, loopStart, seconds, loops, sections, maxDur, fp }. Times in seconds.
   *  lv: optional measured level record { g, p1, p2, tri, noi } (see A.levels) that scales each event via e.g. */
  function compileDef(def, lv) {
    const stepSec = 60 / def.bpm / 4;
    const swing = def.swing || 0;
    const order = def.order.trim().split(/\s+/);
    const events = [];
    const loopIdx = def.loop === undefined ? 0 : def.loop;
    let t0 = 0, loopStart = 0;
    const sections = [];
    order.forEach((name, oi) => {
      const sec = def.sections[name];
      if (oi === loopIdx) loopStart = t0;
      let steps = 0;
      for (const ch of CHANNELS) {
        if (!sec[ch]) continue;
        const inst = instOf(def, ch);
        const pt = parseTrack(sec[ch], ch, inst);
        steps = Math.max(steps, pt.steps);
        for (const it of pt.items) {
          const off = (it.s % 2 === 1 ? swing * stepSec : 0);
          const t = t0 + it.s * stepSec + off;
          if (ch === 'noi') {
            events.push({ t, dur: it.l * stepSec, ch, d: it.drum, vol: it.v / 15 });
          } else {
            const gate = it.arp ? 0.9 : inst.gate;
            const dur = Math.max(0.03, it.l * stepSec * gate);
            const ev = { t, dur, ch, f: hz(it.midi), midi: it.midi, vol: it.v / 15, duty: it.duty, env: it.env };
            const vb = inst.vib;
            if (vb && it.l >= (vb.min || 4) && !it.arp) {
              ev.vib = { rate: vb.rate || 5.5, depth: ev.f * (vb.depth || 0.007), delay: vb.delay === undefined ? 0.14 : vb.delay };
            }
            events.push(ev);
          }
        }
      }
      sections.push({ name, start: t0, steps });
      t0 += steps * stepSec;
    });
    events.sort((a, b) => a.t - b.t || CHANNELS.indexOf(a.ch) - CHANNELS.indexOf(b.ch));
    const fp = fingerprint(events, def.bpm + ':' + (def.kind || ''));
    if (lv) for (const e of events) e.g = (lv.g === undefined ? 1 : lv.g) * (lv[e.ch] === undefined ? 1 : lv[e.ch]);
    const loops = loopIdx >= 0;
    let maxDur = 0;
    for (const e of events) if (e.dur > maxDur) maxDur = e.dur;
    return { events, total: t0, loopStart: loops ? loopStart : 0, seconds: t0, loops, sections, stepSec, maxDur, fp, gain: lv ? lv.g : 1, resume: def.resume !== false };
  }

  // ---------- SFX notation ----------
  // 'wave freq[>freq2] dur [vol] [@start] [ex]' segments separated by ';' (sequential unless @start given).
  function parseSfx(str) {
    const events = [];
    const errors = [];
    let cursor = 0, end = 0;
    for (const raw of String(str).split(';')) {
      const seg = raw.trim();
      if (!seg) continue;
      const tk = seg.split(/\s+/);
      const w = tk[0];
      const fm = /^(\d+(?:\.\d+)?)(?:>(\d+(?:\.\d+)?))?$/.exec(tk[1] || '');
      const dur = parseFloat(tk[2]);
      if (!/^(p[0-3]|t|s|n)$/.test(w) || !fm || !(dur > 0)) { errors.push('bad segment: ' + seg); continue; }
      let vol = 0.5, at = cursor, env = w === 'n' ? 'decay' : 'hold', vib = null;
      for (const x of tk.slice(3)) {
        if (x[0] === '@') at = parseFloat(x.slice(1));
        else if (x[0] === 'e') env = ENV_CODES[x[1]] || env;
        else if (x[0] === 'v') vib = { rate: 9, depth: parseFloat(x.slice(1)) || 6 };
        else if (!isNaN(parseFloat(x))) vol = parseFloat(x);
      }
      const f = +fm[1], f2 = fm[2] ? +fm[2] : f;
      const ev = { t: at, dur, vol, env };
      if (w[0] === 'p') Object.assign(ev, { ch: 'p1', duty: +w[1], f, f2 });
      else if (w === 't') Object.assign(ev, { ch: 'tri', f, f2 });
      else if (w === 's') Object.assign(ev, { ch: 'sin', f, f2 });
      else Object.assign(ev, { ch: 'noi', d: 'n', f, f2 });
      if (vib) ev.vib = vib;
      events.push(ev);
      cursor = at + dur;
      end = Math.max(end, at + dur);
    }
    events.sort((a, b) => a.t - b.t);
    return { events, seconds: end, errors, fp: fingerprint(events, 'sfx'), gain: 1 };
  }

  // ---------- species cries ----------
  function fnv(s) { return fnvStr(String(s)); }
  function mulberry(seed) {
    let s = seed >>> 0 || 1;
    return () => {
      let t = (s = (s + 0x6d2b79f5) >>> 0);
      t = Math.imul(t ^ (t >>> 15), t | 1);
      t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }
  /** All the random choices of a cry, derived from the species id (deterministic). */
  function cryParams(id) {
    if (id && typeof id === 'object') id = id.id !== undefined ? id.id : JSON.stringify(id);
    const r = mulberry(fnv('cry:' + id));
    return {
      base: 190 * Math.pow(2, r() * 2.4), // ~190..~1000 Hz
      contour: Math.floor(r() * 6),
      duty: Math.floor(r() * 4),
      dur: 0.2 + r() * 0.22,
      wob: r() < 0.4,
      n: 2 + Math.floor(r() * 2),
      vrate: 10 + r() * 8,
    };
  }
  /** Build the events of a cry from its parameters (also used by the tuner to measure each contour/duty). */
  function cryFromParams(p) {
    const { base, contour, duty, dur, wob, n, vrate } = p;
    const ev = [];
    const add = (o) => ev.push(Object.assign({ t: 0, vol: 0.9, env: 'hold', ch: 'p1', duty }, o));
    switch (contour) {
      case 0: add({ dur, f: base, f2: base * 1.6 }); break; // rising "mew"
      case 1: add({ dur, f: base * 1.5, f2: base * 0.75 }); break; // falling
      case 2: add({ dur: dur * 0.5, f: base, f2: base * 1.5 }); add({ t: dur * 0.5, dur: dur * 0.5, f: base * 1.5, f2: base * 0.8 }); break; // arch
      case 3: { const d = dur / n; for (let i = 0; i < n; i++) add({ t: i * d, dur: d * 0.7, f: base * (1 + 0.25 * (i % 2)), f2: base * (1.1 + 0.2 * (i % 2)) }); break; } // staccato chirps
      case 4: // growl
        add({ dur, f: base * 0.6, f2: base * 0.5, ch: 'tri', vol: 1 });
        add({ dur: dur * 0.9, f: base * 0.3, f2: base * 0.22, duty: 0, vol: 0.55 });
        ev.push({ t: 0, dur: dur * 0.5, ch: 'noi', d: 'n', f: 900, f2: 400, vol: 0.25, env: 'decay' });
        break;
      default: add({ dur, f: base, f2: base, vib: { rate: vrate, depth: base * 0.08 } }); add({ dur: dur * 0.7, f: base * 1.5, f2: base * 1.5, vol: 0.4, ch: 'tri' }); // warble
    }
    if (wob && contour < 4) ev.forEach((e) => { if (e.ch === 'p1') e.vib = { rate: 14, depth: e.f * 0.04 }; });
    return ev;
  }
  /** Deterministic short "voice" for a species id. Returns { events, seconds, params, fp, gain }. */
  function cryEvents(id) {
    const p = cryParams(id);
    const ev = cryFromParams(p);
    const g = (A.levels.c || {})[p.contour + '.' + p.duty];
    if (g !== undefined) ev.forEach((e) => { e.g = g; });
    return { events: ev, seconds: Math.max(...ev.map((e) => e.t + e.dur)), params: p, gain: g === undefined ? 1 : g };
  }

  // ---------- registry access ----------
  const aliases = {};
  const resolve = (id) => (typeof id === 'string' && aliases[id]) || id;
  function defOf(id) { return NP.data.songs[resolve(id)] || null; }
  A.resolve = resolve;
  A.isJingle = (id) => { id = resolve(id); const d = NP.data.songs[id]; return !!d && (d.kind === 'jingle' || /^j_/.test(id)); };
  A.compile = function (id, o) {
    id = resolve(id);
    const useLv = !o || o.levels !== false;
    const key = useLv ? id : id + '#raw';
    if (cache[key]) return cache[key];
    const d = defOf(id);
    if (!d) return null;
    return (cache[key] = compileDef(d, useLv ? A.levels.m[id] : null));
  };
  A.sfxEvents = function (id, o) {
    const useLv = !o || o.levels !== false;
    const k = 'sfx:' + id + (useLv ? '' : '#raw');
    if (cache[k]) return cache[k];
    const d = NP.data.sfx[id];
    if (d === undefined) return null;
    const r = parseSfx(typeof d === 'string' ? d : d.seq);
    const g = useLv ? A.levels.s[id] : undefined;
    if (g !== undefined) { r.events.forEach((e) => { e.g = g; }); r.gain = g; }
    return (cache[k] = r);
  };
  A.cryEvents = cryEvents;
  A.songs = () => Object.keys(NP.data.songs).filter((k) => !A.isJingle(k));
  A.jingles = () => Object.keys(NP.data.songs).filter((k) => A.isJingle(k));
  A.sfxs = () => Object.keys(NP.data.sfx);
  A.aliases = () => Object.assign({}, aliases);
  /** Register `alias` as another name for the existing song `canonical` (non-enumerable, so songs() lists each tune once). */
  A.alias = function (alias, canonical) {
    if (!NP.data.songs[canonical]) throw new Error('alias target missing: ' + canonical);
    if (NP.data.songs[alias] && !aliases[alias]) throw new Error('alias collides with song ' + alias);
    aliases[alias] = canonical;
    Object.defineProperty(NP.data.songs, alias, { value: NP.data.songs[canonical], enumerable: false, configurable: true, writable: true });
  };
  A.info = function (id) {
    id = resolve(id);
    if (id in NP.data.songs) {
      const c = A.compile(id);
      return { kind: A.isJingle(id) ? 'jingle' : 'song', seconds: c.seconds, loops: c.loops };
    }
    if (id in NP.data.sfx) return { kind: 'sfx', seconds: A.sfxEvents(id).seconds, loops: false };
    return null;
  };

  /** Validate one song by id; returns an array of problem strings (empty = fine). */
  A.validate = function (id) {
    id = resolve(id);
    const def = defOf(id);
    const out = [];
    const bad = (s) => out.push(id + ': ' + s);
    if (!def) { bad('missing'); return out; }
    const jingle = A.isJingle(id);
    if (!(def.bpm >= 40 && def.bpm <= 240)) bad('bpm out of range');
    const bar = def.bar || 16;
    if (![4, 8, 12, 16, 24].includes(bar)) bad('unusual bar length ' + bar);
    if (!def.order || !def.sections) { bad('no order/sections'); return out; }
    const order = def.order.trim().split(/\s+/);
    if (jingle ? def.loop !== -1 : !(Number.isInteger(def.loop) && def.loop >= 0 && def.loop < order.length)) bad('bad loop index');
    if (def.inst) {
      for (const ch of Object.keys(def.inst)) {
        if (!CHANNELS.includes(ch)) { bad('unknown inst channel ' + ch); continue; }
        const v = def.inst[ch];
        if (v.vol !== undefined && !(v.vol >= 0 && v.vol <= 15)) bad(`inst.${ch}.vol out of range`);
        if (v.duty !== undefined && ![0, 1, 2, 3].includes(v.duty)) bad(`inst.${ch}.duty out of range`);
        if (v.env !== undefined && !Object.values(ENV_CODES).includes(v.env)) bad(`inst.${ch}.env unknown`);
      }
    }
    for (const name of order) {
      const sec = def.sections[name];
      if (!sec) { bad('unknown section ' + name); continue; }
      let steps = -1;
      for (const ch of CHANNELS) {
        if (!sec[ch]) { if (!jingle || ch === 'p1') bad(`section ${name} lacks ${ch}`); continue; }
        const pt = parseTrack(sec[ch], ch, instOf(def, ch));
        for (const e of pt.errors) bad(`${name}.${ch}: ${e}`);
        if (pt.steps % bar) bad(`${name}.${ch}: ${pt.steps} steps is not a multiple of bar=${bar}`);
        pt.bars.forEach((b, i) => { if (b % bar) bad(`${name}.${ch}: bar ${i + 1} ends at step ${b} (bar=${bar})`); });
        if (steps < 0) steps = pt.steps;
        else if (pt.steps !== steps) bad(`${name}.${ch}: ${pt.steps} steps, expected ${steps}`);
        for (const it of pt.items) {
          if (it.midi === undefined) continue;
          const lo = ch === 'tri' ? 24 : 36, hi = ch === 'tri' ? 72 : 100;
          if (it.midi < lo || it.midi > hi) bad(`${name}.${ch}: note ${nameOf(it.midi)} out of range`);
        }
      }
    }
    const c = compileDef(def, null);
    if (!c.events.length) bad('no events');
    if (!jingle && c.loops && c.total - c.loopStart < 12) bad('loop shorter than 12s');
    if (!jingle && c.total < 20) bad('song shorter than 20s');
    if (jingle && c.total > 12) bad('jingle longer than 12s');
    if (!jingle && !(typeof def.desc === 'string' && def.desc.length >= 8)) bad('missing desc (mood / where it is used)');
    return out;
  };

  // ---------- DSL helpers for song authors ----------
  // arp(['Am','F,G'], 3)   -> '^Am3:16 | ^F3:8 ^G3:8 |'   (comma = split the bar)
  // bass(['Am','F'], '1:4 1:2 5:2 ...', 2) -> root/fifth/octave/third/seventh patterns ('1','3','5','7','8'); patterns are per-bar (truncated for split bars)
  const split = (c) => c.split(',');
  function dslArp(chords, oct, bar) {
    bar = bar || 16;
    return chords.map((c) => {
      const p = split(c);
      const l = bar / p.length;
      return p.map((x) => '^' + x + oct + ':' + l).join(' ');
    }).join(' | ') + ' |';
  }
  function truncate(pat, steps) {
    const out = [];
    let used = 0, len = 2;
    for (const tok of pat.trim().split(/\s+/)) {
      const [h, l] = tok.split(':');
      if (l !== undefined) len = +l;
      if (used >= steps) break;
      const use = Math.min(len, steps - used);
      out.push(h + ':' + use);
      used += use;
    }
    return out.join(' ');
  }
  function dslBass(chords, pat, oct, bar) {
    bar = bar || 16;
    return chords.map((c) => {
      const p = split(c);
      const l = bar / p.length;
      return p.map((x) => {
        const ch = chord(x + oct);
        if (!ch) throw new Error('bass chord ' + x);
        const T = { 1: 0, 3: ch.tones[1] - ch.root, 5: ch.tones[2] - ch.root, 7: ch.tones[3] - ch.root, 8: 12, 4: 5 };
        const base = truncate(pat, l);
        return base.split(' ').map((tok) => {
          const [h, len] = tok.split(':');
          return h === 'r' ? 'r:' + len : nameOf(ch.root + T[h]) + ':' + len;
        }).join(' ');
      }).join(' ');
    }).join(' | ') + ' |';
  }
  // comp(['Fmaj7','D7'], 'r:2 X:3 r:5 X:3 r:3', 4)  -> chord stabs: every X becomes the bar's chord as a short arpeggio (^Chord)
  function dslComp(chords, pat, oct, bar) {
    bar = bar || 16;
    return chords.map((c) => {
      const p = split(c);
      const l = bar / p.length;
      return p.map((x) => truncate(pat, l).split(' ').map((tok) => {
        const [h, len] = tok.split(':');
        return h === 'X' ? '^' + x + oct + ':' + len : h + ':' + len;
      }).join(' ')).join(' ');
    }).join(' | ') + ' |';
  }
  // weave(['Bb','Gm'], 4, [0,1,2,1], 16, 1) -> explicit broken-chord notes using chord-tone indexes (0 root,1 third,2 fifth,3 octave/7th)
  function dslWeave(chords, oct, pat, bar, len) {
    bar = bar || 16; pat = pat || [0, 1, 2, 1]; len = len || 1;
    return chords.map((c) => {
      const p = split(c);
      const l = bar / p.length;
      return p.map((x) => {
        const ch = chord(x + oct);
        if (!ch) throw new Error('weave chord ' + x);
        const n = Math.floor(l / len);
        const out = [];
        for (let i = 0; i < n; i++) out.push(nameOf(ch.tones[pat[i % pat.length]]) + ':' + len);
        if (l - n * len) out.push('r:' + (l - n * len));
        return out.join(' ');
      }).join(' ');
    }).join(' | ') + ' |';
  }
  // transposition helpers for sequences: tr(str, semitones), dtr(str, scaleSteps, 'D major')
  const MODES = {
    major: [0, 2, 4, 5, 7, 9, 11], minor: [0, 2, 3, 5, 7, 8, 10], dorian: [0, 2, 3, 5, 7, 9, 10], phrygian: [0, 1, 3, 5, 7, 8, 10],
    lydian: [0, 2, 4, 6, 7, 9, 11], mixolydian: [0, 2, 4, 5, 7, 9, 10], harmonic: [0, 2, 3, 5, 7, 8, 11], hijaz: [0, 1, 4, 5, 7, 8, 10],
    pentatonic: [0, 2, 4, 7, 9], minpent: [0, 3, 5, 7, 10],
  };
  const NOTE_TOKEN = /^([a-g][#b]?\d)(:\d+)?$/;
  const mapNotes = (str, fn) => String(str).split(/(\s+)/).map((tok) => {
    const m = NOTE_TOKEN.exec(tok);
    return m ? nameOf(fn(midiOf(m[1]))) + (m[2] || '') : tok;
  }).join('');
  function dslTr(str, semis) { return mapNotes(str, (m) => m + semis); }
  function dslDtr(str, n, key) {
    const [tn, mode] = key.split(' ');
    const tonic = PC[tn[0].toLowerCase()] + (tn[1] === '#' ? 1 : tn[1] === 'b' ? -1 : 0);
    const steps = MODES[mode];
    if (!steps) throw new Error('unknown mode ' + mode);
    const len = steps.length;
    return mapNotes(str, (m) => {
      const rel = m - tonic;
      const oct = Math.floor(rel / 12);
      const pcr = rel - oct * 12;
      let d = 0;
      for (let i = 0; i < len; i++) if (steps[i] <= pcr) d = i;
      const acc = pcr - steps[d];
      const idx = oct * len + d + n;
      const o2 = Math.floor(idx / len);
      return tonic + o2 * 12 + steps[idx - o2 * len] + acc;
    });
  }
  A.dsl = {
    arp: dslArp, bass: dslBass, comp: dslComp, weave: dslWeave, tr: dslTr, dtr: dslDtr,
    rep: (s, n) => '[ ' + s + ' ]x' + n,
    x: (s, n) => (s + ' ').repeat(n).trim(), // plain repetition (keeps '|' bar markers visible to the validator)
  };

  /** Register a song. def: { bpm, bar?, swing?, inst?, loop, order, sections, kind?, desc, resume? } */
  A.song = function (id, def) {
    if (NP.data.songs[id]) throw new Error('duplicate song ' + id);
    NP.data.songs[id] = def;
    return def;
  };
  A.sfxDef = function (table) {
    for (const k of Object.keys(table)) {
      if (NP.data.sfx[k]) throw new Error('duplicate sfx ' + k);
      NP.data.sfx[k] = table[k];
    }
  };

  A.MIX = MIX;
  A.notation = {
    midiOf, nameOf, hz, chord, parseTrack, expand, compileDef, parseSfx, cryParams, cryFromParams, voices, envPoints, pulseComp, fingerprint,
    DUTY, CHANNELS, DRUMS, DEFAULT_INST, MIX, ENV_CODES,
  };
})(typeof globalThis !== 'undefined' ? globalThis : window);
