// Regenerates the <script> block of index.html from the per-area manifests, so several people/agents
// can add files without ever editing index.html at the same time.
//
//   node tools/build-index.mjs
//
// Each area keeps `src/<area>/files.json` — a JSON array of script paths (relative to the project
// root, in load order). The global order of areas lives in ORDER below. Re-run after changing any manifest.
import fs from 'node:fs';
import path from 'node:path';
import { ROOT } from './load.mjs';

const CORE = ['src/core/color.js', 'src/core/rng.js', 'src/core/bitmap.js', 'src/core/font.js', 'src/core/ns.js'];

// [manifest path | literal script, browserOnly?]
const ORDER = [
  ...CORE.map((f) => [f]),
  ['src/art/kigu/files.json'],
  ['src/art/human/files.json'],
  ['src/art/tiles/files.json'],
  ['src/art/icons/files.json'],
  ['src/audio/files.json'],
  ['src/data/files.json'],
  ['src/maps/files.json'],
  ['src/engine/files.json'],
  ['src/game/files.json'],
  ['src/platform/browser.js', true],
];

const lines = [];
for (const [p, browser] of ORDER) {
  if (p.endsWith('.json')) {
    const f = path.join(ROOT, p);
    if (!fs.existsSync(f)) continue;
    const list = JSON.parse(fs.readFileSync(f, 'utf8'));
    lines.push(`<!-- ${p} -->`);
    for (const s of list) lines.push(`<script src="${s}"></script>`);
  } else if (fs.existsSync(path.join(ROOT, p)) || browser) {
    lines.push(`<script src="${p}"${browser ? ' data-browser' : ''}></script>`);
  }
}

const file = path.join(ROOT, 'index.html');
let html = fs.readFileSync(file, 'utf8');
const begin = '<!-- BEGIN SCRIPTS (generated by tools/build-index.mjs — do not edit by hand) -->';
const end = '<!-- END SCRIPTS -->';
const block = begin + '\n' + lines.join('\n') + '\n' + end;
if (html.includes('<!-- BEGIN SCRIPTS')) html = html.replace(/<!-- BEGIN SCRIPTS[\s\S]*?<!-- END SCRIPTS -->/, block);
else html = html.replace(/(<script src="src\/core\/color\.js"><\/script>[\s\S]*?<script src="src\/core\/font\.js"><\/script>)/, block);
fs.writeFileSync(file, html);
console.log(`index.html: ${lines.filter((l) => l.startsWith('<script')).length} scripts`);
